---
title: "Biology 381 - Computational Biology"
author: "Nicholas J. Gotelli"
date: "Spring 2018"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---


This site contains course materials, scripts, homeworks, and resources for Computational Biology, Spring 2018.

## Course Materials

[Software Installation](CourseMaterials/SoftwareInstallation.html)

[Course Syllabus](CourseMaterials/CourseSyllabus.html)   
[Course Syllabus (pdf)](CourseMaterials/CourseSyllabus.pdf)   

[Lecture Outlines](Lectures/LectureOutlines.html)   

[R Scripts](Scripts/RScripts.html)

[Cheat Sheets & Programming Resources](CheatSheets/CheatSheets.html)

___

## Lecture Outlines, R-Scripts, & Homework Assignments

Date  | Lecture | Scripts  | Homework
------------- | -------------- |----------- | -------------
January 16  | [GitHub](Lectures/Lecture01.html) | -  | -
January 17  | - | -  | [Homework #1](Homeworks/Homework01_2018.html)
January 18  | [Thinking On Paper](Lectures/Lecture02.html) | -  | -
January 23  | [RStudio](Lectures/Lecture03_4.html) | - | -
January 24  | - | -  | [Homework #2](Homeworks/Homework02_2018.html)
January 25  | [RStudio II](Lectures/Lecture03_4.html) | -| -
January 30  | [Beamer Slides](Lectures/Lecture05.html) | [R-Scripts](https://gotellilab.github.io/Bio381/Scripts/RScripts.html) | -
January 31  | - | -  | [Homework #3](Homeworks/Homework03_2018.html)
February 1  | [Atomic Vectors](Lectures/Lecture06_2018.html) | [R-Scripts](https://gotellilab.github.io/Bio381/Scripts/RScripts.html)  | -
February 6  | [Regular Expressions](Lectures/Lecture07_8.html)| [R-Scripts](https://gotellilab.github.io/Bio381/Scripts/RScripts.html)  | -
February 7  | - | -  | [Homework #4](Homeworks/Homework04_2018.html)
February 8  | [Regular Expressions II](Lectures/Lecture07_8.html)| [R-Scripts](https://gotellilab.github.io/Bio381/Scripts/RScripts.html)  | -
February 13  | [Probability Distributions I](Lectures/Lecture08_2018.html)| [R-Scripts](https://gotellilab.github.io/Bio381/Scripts/RScripts.html)  | -
February 14  | - | -  | [Homework #5](Homeworks/Homework05_2018.html)
February 15  | [Data Structures](Lectures/Lecture10.html)| -  | -
February 20  | [Probability Distributions II](Lectures/Lecture08_2018)| -  | -
February 21  | - | -  | [Homework #6](Homeworks/Homework06_2018.html)
February 22  | [Data Entry, Experimental Designs](Lectures/Lecture12_2018.html)| -  | -
February 27  | [Regression,ANOVA Designs](Lectures/Lecture13_2018.html)| -  | -
February 28  | - | -  | [Homework #7](Homeworks/Homework07_2018.html)
March 1  | [Functions](Lectures/Lecture14_2018.html)| -  | -
March 6  | *TOWN MEETING DAY RECESS* | -  | -
March 7  | - | -  | [Homework #8](Homeworks/Homework08_2018.html)
March 8  | [Structured Programming](Lectures/Lecture15_2018.html) | [R-Scripts](https://gotellilab.github.io/Bio381/Scripts/RScripts.html)  | -
March 13  | *SPRING RECESS* | -  | -
March 14  | *SPRING RECESS* | -  | -
March 15  | *SPRING RECESS* | -  | -
March 20  | [Control Structures I](Lectures/Lecture16_2018.html) | -  | -
March 21  | - | -  | [Homework #9](Homeworks/Homework09_2018.html)
March 22  | [Control Structures II](Lectures/Lecture17_2018.html) | - | -
March 27  | [Batch Processing](Lectures/Lecture18_2018.html) | -  | -
March 28  | - | -  | [Homework #10](Homeworks/Homework10_2018n.html)
March 29  | [Plotting Mathematical Functions](Lectures/Lecture19_2018.html) | -  | -
April 3  | [Randomization Tests](Lectures/Lecture20_2018.html) | -  | -
April 4  | - | -  | [Homework #11](Homeworks/Homework11_2018.html)
April 5  | [ggplot I](Lectures/Lecture21_2018.html) | -  | -
April 10  | [ggplot II](Lectures/Lecture22_2018.html) | -  | -
April 11  | - | -  | [ggplot Graphing](Homeworks/Homework12_2018.html)
April 12  | [ggplot III](Lectures/Lecture23_2018.html) | -  | -
April 17  | [Markov Models II](Lectures/Lecture22.html) | -  | -
April 18  | - | -  | Catch-up Day (no homework assignment)
April 19  | [Apply Functions](Lectures/Lecture23.html) | -  | -
April 24  |**Presentations: Barlow, Rewcastle, Looney** | -  | -
April 25  | - | -  |**Presentations: Burns, Daniels, Neidermeier, Page, Pett**
April 26  |**Presentations: Thibault, Yancey** | -  | -
May 1  | **Presentations: Wieghan, Verrico**| -  | -
May 2  | -  | -  | **Presentations: Dittmer, Hackenberg, Ruizarocho, Schmoker, Steinhart**
May 3  | **Palawat, Bomeisl** | -  | -

### Class Work

Student  | Fun Fact
------------- | --------------
Lauren Ash  [GitHub](https://github.com/lvash) [Portfolio](https://lvash.github.io/Bio381/)  | While interning at Busch Gardens in Florida, I made friends with [Rosie the elephant](https://cloud.githubusercontent.com/assets/15003012/22121503/61755fec-de52-11e6-9a65-16b0e926c247.jpg) because she would sway and stare at me for hours.
John Barlow [GitHub](https://github.com/johnbarlowvt) [Portfolio](https://johnbarlowvt.github.io/Bio381_2018/)  | I once gave a snake an enema.
Lauren Bomeisl [GitHub](https://github.com/laurenbomeisl) [Portfolio](https://laurenbomeisl.github.io/Bio381_2018/)  | I have jumped off the most southern point of the US (south point, big island of Hawaii).
Wilton Burns [GitHub](https://github.com/wgburns) [Portfolio](https://wgburns.github.io/Bio381_2018/)  | I play the violin in the Amateur Musicians Orchestra, a local Burlington group.
Luke Daniels [GitHub](https://github.com/x) [Portfolio](https://lukedaniels1.github.io/Bio381_2018/)  | I met Matthew Perry (Chandler from the T.V show Friends), and I play the guitar.
Kyle Dittmer [GitHub](https://github.com/kyledittmer) [Portfolio](https://kyledittmer.github.io/Bio381_2018/)  | This is my first winter ever living in snow!
Nick Gotelli [GitHub](https://github.com/GotelliLab) [Portfolio](https://gotellilab.github.io/Bio381/)  | For 33 years, I have raised pure-bred, show-quality [chow chows.](https://en.wikipedia.org/wiki/Chow_Chow)
Diana Hackenberg [GitHub](https://github.com/dhackenburg) [Portfolio](https://dhackenburg.github.io/Bio381_2018/)  | I play the French Horn.
Raymond Looney [GitHub](https://github.com/rlooney) [Portfolio](https://rlooney.github.io/Bio381_2018/)  | I'm an actor, and in a play I was in last year I got so committed to a scene that I broke my foot while kicking a box and continued the performance for 3 more days.
Alex Neidermeier [GitHub](https://github.com/aneiderm) [Portfolio](https://aneiderm.github.io/NeiderBio381/)  | While in the Peace Corps in Burkina Faso, my main project was, bizarrely enough, working with a women’s group on making and selling tofu kebobs at a local bar.
Owen Page [GitHub](https://github.com/owenrpage/Biol381_2018/) [Portfolio](https://owenrpage.github.io/Biol381_2018/)  | I am a pretty big Newcastle United fan and used to play classical guitar.
Kunal Palawat [GitHub](https://github.com/kpalawat223) [Portfolio](https://kpalawat223.github.io/CompBiol381/)  | I have been consistently vegetarian and inconsistently vegan since birth.
Lindsey Pett [GitHub](https://github.com/lpett) [Portfolio](https://lpett.github.io/Bio381_2018/)  | I just became a pet parent to 3 dwarf puffer fish.
Kenna Rewcastle [GitHub](https://github.com/kennarewcastle) [Portfolio](https://kennarewcastle.github.io/RewcastleBio381/)  | My most epic `#fieldworkfail` involved a bike wreck with a reindeer.
Jorge Ruizarocho [GitHub](https://github.com/jorgeruizarocho) [Portfolio](https://jorgeruizarocho.github.io/Bio381_2018/)  | My native language is Spanish and I am a mixture of Europeans, Africans and Native Americans (aka. a Puerto Rican).
Anna Schmoker [GitHub](https://github.com/aschmoke) [Portfolio](https://aschmoke.github.io/Bio381_2018/)  | I teach ballet and worked as a professional ballet dancer before coming to UVM.
Anya Steinhart [GitHub](https://github.com/anyasteinhart9898) [Portfolio](https://anyasteinhart9898.github.io/BIOL-381/)  | I am a certified yoga instructor.
Ethan Thibault [GitHub](https://github.com/ethanthibault) [Portfolio](https://ethanthibault.github.io/BIO381/)  |I have helped my dad with his landscaping business for nine years and as a result can operate commercial landscaping equipment such as zero-turn mowers, leaf-vacs, gas powered backpack blowers, hedge trimmers, etc.
Brittany Verrico [GitHub](https://github.com/bmverrico) [Portfolio](https://bmverrico.github.io/Bio381_ComputationalBiology/)  | I primarily read WWII literature for pleasure.
Adrian Wiegman [GitHub](https://github.com/arhwiegman) [Portfolio](https://arhwiegman.github.io/Bio381_2018/)  | I once caught about 20 speckled trout and redfish in 1 hour while fishing under a spotlight on a dock at night in Grand Isle Louisiana. Other than that I am a rather terrible fisherman.
Colleen Yancey [GitHub](https://github.com/cyancey95/CompBiol_2018) [Portfolio](https://cyancey95.github.io/CompBiol_2018/)  | My dad is a Commander in the Navy which means I had moved 6 times before I turned 8 years old.

### Class R Presentations

Author | Title
-------| --------
John Barlow| [Comparing Microbe Diversity With `made4`](StudentPresentations/x.html)
Lauren Bomeisl | [Accessing Elevation Data With `elevatr`](StudentPresentations/x.html)
Wilton Burns | [Analyzing Meteorological And Time Series Data With `openair`](StudentPresentations/x.html)
Luke Daniels | [Cluster Analysis With  `cluster`](StudentPresentations/x.html)
Kyle Dittmer | [Formatting Time Data With `lubridate`](StudentPresentations/x.html)
Diana Hackenberg | [Creating Interactive Time Lines With  `timevis`](StudentPresentations/x.html)
Raymond Looney| [Interactive Maps With `leaflet`](StudentPresentations/x.html)
Alex Neidermeier | [Creating Spatial Maps With `ggmap`](StudentPresentations/x.html)
Owen Page | [Modeling Disease Dynamics With `EpiModel`](StudentPresentations/x.html)
Kunal Palawat | [Analyzing Microbial Diversity Data With `mctoolsr`](StudentPresentations/x.html)
Lindsey Pett | [Biodiversity Analysis With `Cheddar`](StudentPresentations/x.html)
Kenna Rewcastle | [Meta-analysis With `metafor`](StudentPresentations/x.html)
Jorge Ruizarocho | [Analyzing Agriculture Data With  `agricolae`](StudentPresentations/x.html)
Anna Schmoker | [Data-wrangling With `base R`](StudentPresentations/x.html)
Anya Steinhart | [3-dimensional Plotting With `scatterD3`](StudentPresentations/x.html)
Ethan Thibault | [??? With `???`](StudentPresentations/x.html)
Brittany Verrico | [Data Wrangling With  `dplyr`](StudentPresentations/x.html)
Adrien Wiegen | [Accessing Financial Data With  `quandl`](StudentPresentations/x.html)
Colleen Yancey | [Creating Tables With `gridExtra`](StudentPresentations/x.html)
