---
title: 'Lecture #08: Data Structures'
author: "Nicholas J. Gotelli"
date: "February 8, 2018"
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---
### Matrices

```{r,eval=FALSE}
library(ggplot2)
# Create a matrix from an atomic vector
m <-matrix(data=1:12,nrow=4,ncol=3)
print(m)

# Must specify at least one of the two dimensions
m <- matrix(data=1:12,nrow=4)
print(m)

# use byrow=TRUE to fill one row at a time
m <-matrix(data=1:12,nrow=4,byrow=TRUE)
print(m)

# use dim() to see dimensions
dim(m)

# can also change dimensions of matrix (must be correct size)
dim(m) <- c(6,2)
print(m)
dim(m) <- c(4,3)
print(m)
# to get separate components of dim
nrow(m)
ncol(m)

# note that length still applies to original atomic vector
length(m)

# to add names 
rownames(m) <- c("a","b","c","d")
print(m)
colnames(m) <- LETTERS[1:ncol(m)]
print(m)
rownames(m) <- letters[nrow(m):1]
print(m)

# specify particular elements within matrix with brackets and subscripts

# print a single element
# print row 2, column 3 
print(m[2,3])
# print an entire row (or column) by leaving entry blank
# print row 2, showing all of the columns
print(m[2,])

#print column 3, showing all of the rows
print(m[,3])

#print everything
print(m)
print(m[,])
print(m[])
# (check help on LETTERS)
rownames(m) <- paste("Species",LETTERS[1:nrow(m)],sep="")
colnames(m) <- paste("Site",1:ncol(m),sep="")
print(m)

# also add names through dimnames function

dimnames(m) <- list(paste("Site",1:nrow(m),sep=""),
                    paste("Species",LETTERS[1:ncol(m)],sep=""))
print(m)

# transpose a matrix with t
m2 <- t(m)
print(m2)

# add a row to m with rbind
m2 <- rbind(m2,c(10,20,30,40))
print(m2)

# now fix the label
rownames(m2)
print(m2)
rownames(m2)[4] <- "myfix"
print(m2)

# Access individual rows and columns with names as well as indices

m2["myfix","Site3"] # equivalent to m2[4,3]
m2[c("SpeciesC","myfix"),c("Site3","Site4")] # note use of c function here!

# use cbind to add columns to the matrix

# can always change this back to a vector at any time:

myVec <- as.vector(m)
print(myVec)
```

### Lists

```{r,eval=FALSE}
# Lists are atomic vectors but each element 
# can hold things of different types and different sizes

myList <- list(1:10, matrix(1:8,nrow=4,byrow=TRUE), letters[1:3],pi)
str(myList)
print(myList)


# using [] gives you a single item, which is of type list
myList[4]
myList[4] - 3 # no, can't subtract a number from a list!


# single brackets gives you only the element in that slot, which is always of type list

# to grab the object itself, use [[]]
myList[[4]]
myList[[4]] - 3 # now we have the contents

# if a list has 10 elements it is like a train with 10 cars
# [[5]] gives you the contents of car #5
##[c(4,5,6)] gives you a little train with cars 4, 5, and 6

# once the double bracket is called, you can access individual elements as before

myList[[2]]
myList[[2]][4,1]

# name list items when they are created

myList2 <- list(Tester=FALSE,littleM=matrix(1:9,nrow=3))

# named elements can be accessed with dollar sign

myList2$littleM[[2,3]] # get row 2, column3
myList2$littleM # show whole matrix
myList2$littleM[2,] # show second row, all columns
myList2$littleM[2] # what does this give you?

# The "unlist" strings everything back into
# a single atomic vector; coercion is used if there are mixed data types
unRolled <- unlist(myList2)
print(unRolled)


# The most common use of list: output from a linear model is a list


y <- runif(10)
x <- runif(10)
myModel <- lm(y~x)
plot(x=x,y=y)
plot(myModel)

# look at output in myModel
print(myModel)

# full results are in summary
print(summary(myModel))

# drill down into summary to get what we want
str(summary(myModel))
summary(myModel)$coefficients
summary(myModel)$coefficients["x","Pr(>|t|)"]
summary(myModel)$coefficients[2,4]


```

### Data Frames

```{r,eval=FALSE}
# a data frame is a list of equal-lengthed vectors, each of which is a column

varA <- 1:12
varB <- rep(c("Con","LowN","HighN"),each=4)
varC <- runif(12)
dFrame <- data.frame(varA,varB,varC,stringsAsFactors=FALSE)
print(dFrame)
str(dFrame)

# add another row with rbind
# make sure you add a list, with each item corresponding to a column

# newData <- data.frame(list(varA=13,varB="HighN",varC=0.668),stringsAsFactors=FALSE)
newData <- list(varA=13,varB="HighN",varC=0.668)
print(newData)
str(newData)

# now bind them
dFrame <- rbind(dFrame,newData)
str(dFrame)
tail(dFrame)


# adding another column is a little easier

#newVar <- data.frame(varD=runif(13))
newVar <- runif(13)
dFrame <- cbind(dFrame,newVar)
head(dFrame)

```

### Important Distinctions Between Lists and Matrices

```{r, eval=FALSE}

# create a matrix and data frame with same structures
zMat <- matrix(data=1:30,ncol=3,byrow=TRUE)
zDframe <- as.data.frame(zMat) # coerce it

str(zMat)    # an atomic vector with 2 dimensions
str(zDframe) # note horizontal layout of variabes!

head(zDframe) # note automatic variable names
head(zMat) # note identical layout

# element referencing is the same in both
zMat[3,3]
zDframe[3,3]

# so is column referencing

zMat[,3]
zDframe[,3]
zDframe$V3 # note use of $ and named variable column
# and row referencing
zMat[3,]
zDframe[3,] # note variable names and row number shown

# what happens if we reference only one dimension?

zMat[2] # takes the second element of atomic vector (column fill)
zDframe[2] # takes second atomic vector (= column) from list
zDframe["V2"]
zDframe$V2
```

### A real application: stripping NA values from a data frame

```{r, eval=FALSE}
# create matrix
m <- matrix(1:20,nrow=5,byrow=TRUE)

# contaminate it
m[1,2] <- NA
m[5,1] <- NA
print(m)

# how do we find NA values?
is.na(m)

# for a single row, we could try:
sum(is.na(m[1,]))

# but how do we get something like this for all rows?
rowSums(m)

# instead of sums, let's get true for na values
is.na(rowSums(m))

# now let's get true for those without na values
!is.na(rowSums(m))

# now we can use this to pull rows that we want
mClean <- m[!is.na(rowSums(m)),]
print(mClean)

# also, we can compile the contaminated rows
mDirty <- m[is.na(rowSums(m)),]
print(mDirty)
```

#### Making our code more general
```{r eval=FALSE}

# using Poisson distribution
# random independent events occurring at a constant (average rate)
# distribution is of frequency of integers (0,1,2....)
# that would be the number of events in a fixed interval
# minimum= 0, maximum= unbounded integer

hits <- rpois(n=1000,lambda=0.2)
qplot(x=hits)
table(hits)

# introduce a small set of global variables

library(ggplot2)
rowM <- 10 # number of rows in matrix
colM <- 5 # number of columns in matrix
lambdaM <- 10 # average number of NA values in matrix

# create matrix
m <- matrix(seq_len(rowM*colM),nrow=rowM,byrow=TRUE)
head(m)

# determine number of NA values (random)
missingN <- rpois(n=1,lambda=lambdaM)

# choose random elements to convert to NA
NAindex <- sample(seq_along(m),size=missingN)
print(NAindex)
# assign these to the corresponding elements of atomic vector
m[NAindex] <- NA
print(m)

# peek at the matrix
head(m)
tail(m)

# how many missing values?
sum(is.na(m))

mClean <- m[!is.na(rowSums(m)),]
print(mClean)
mDirty <- m[is.na(rowSums(m)),]
print(mDirty)


# And now the easy way
mClean <- na.omit(m)
print(mClean)
str(mClean)
```

