---
title: 'Lecture #6: Creating and Importing Data'
author: "Nicholas J. Gotelli"
date: "February 2, 2017"
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---
### Creating Data Frames
- Each row is the *smallest possible sampling unit*
- Each column is an *attribute* measured for the sampling unit
- All elements in the same column are of the same data type
- All columns are of the same length
- Missing data as `NA`
- Variable names: no spaces or special characters
- ID variable as first entry. Consecutive number `0001`
- Dates as characters suggest 02Feb2017 then use `as.date()` later

### Long versus Short Forms For Data Frames
- go to webpage to see results for two structures
- packages to convert between them

### Creating MetaData
- Embed in data file
- Use `#` to add any notes; R skips this line when reading data
- Time consuming but important

### Sample MetaData Sheet in Excel
- Discuss individual entries
- Discuss idea of separate metasheet
- Modifications of data could be part of version control in git

### Importing Data Into R
- get `antcountydata.csv` from course website


```{r, eval=FALSE}
# Read in csv
z <- read.table("antcountydata.csv",header=TRUE,row.names=1,sep=",", stringsAsFactors=FALSE)

# Basic check for data formats with structure
str(z)

# Basic check for outlier numerical values
summary(z)

# Basic check for character string variables
table(z$state) # one way check for state names
table(z$ecoregion) # one way check for ecoregion names
table(z$state,z$ecoregion) # two-way classification

```

### Simple Error Checking
- `str(z)` for structure of data frame
- `summary(z)` for stats on numeric variables
- `table(z$state)` classification for character variables
- `table(z$state,z$ecoregion` cross classification
