---
title: 'Lecture #5: Regular Expressions'
author: "Nicholas J. Gotelli"
date: "September 10, 2018"
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---
## Regular Expressions

### Set up for BBedit
- increase font size
- soft wrap on screen
- regex on
- case sensitive on
- wrap off

### Use of literals in searches
```
STRING: A sentence. Another. And a third.
SEARCH: .
RESULT: finds the periods

with Regex (or grep) search

STRING: A sentence. Another. And a third.
SEARCH: .
RESULT: finds every consecutive character and space!
```
### Escaping a metacharacter

- insert a `\` before special characters for a literal search in regex

```
STRING: A sentence. Another. And a third.
SEARCH: \.
RESULT: finds the periods
```
### Wildcards
- `\w` a single word character [letter,number or `_`]
- `\d` a single number character [0-9]
- `\t` a single tab space
- `\s` a single space, tab, or line break
- `\n` a single line break (or try `\r`)

```
STRING: crow raven grackle
SEARCH: \s
REPLACE: \n
RESULT: 
crow
raven
grackle
```

#### Repairing pdf cut and paste
```
STRING:
Cutting and
pasting from pdf is
a mess. Sentences
are
all chopped up. It is
hard
to repair.

SEARCH: \n
REPLACE: (replace with nothing)
RESULT: 
Cutting and pasting from pdf is a mess. Sentences are all chopped up. It is hard to repair. 
```
- TRY THIS WITH AN ACTUAL PDF PARAGRAPH

### Quantifiers
- add these on to any of the wildcards

- `\w+` one or more consecutive word characters
- `\w*` zero or more consecutive word characters
- `\w{3}` exactly 3 consecutive word characters
- `\w{3,}` 3 or more consecutive word characters
- `\w{3,5}` 3, 4, or 5 consecutive word characters

#### Using a zero or more * quantifier

```
STRING: crow, raven ,grackle,starling  ,    robin
SEARCH: \s*,\s*
REPLACE: , 
RESULT: crow,raven,grackle,starling,robin
```
#### Using .* for "all the rest"

```
STRING: 
x, MyWord OtherJunk. ,
13, MyWord2,OtherStuff,,
X13,   MyThirdWord,        MoreTrash,!##
xxx,LastWord     x.

SEARCH: \w+,\s*\w+.*
RESULT: Matches each line completely!
```
#### Captures for the replacement string

```
STRING: 
x, MyWord OtherJunk. ,
13, MyWord2,OtherStuff,,
X13,   MyThirdWord,        MoreTrash,!##
xxx,LastWord     x.

SEARCH: \w+,\s*\w+.*

SEARCH (with capture): \w+,\s*(\w+).*
REPLACE: \1
RESULT:
MyWord
AnotherOfMyWords
MyThirdWord
```
### Adding multiple captures and literal text
```
STRING: 
x, MyWord OtherJunk. ,
13, MyWord2,OtherStuff,,
X13,   MyThirdWord,        MoreTrash,!##
xxx,LastWord     x.

SEARCH: \w+,\s*\w+.*
SEARCH: \w+,\s*(\w+)(.*)
REPLACE: MY WORD: \1\s LEFTOVER: \2
RESULT:
MY WORD: MyWord LEFTOVER:  OtherJunk. ,
MY WORD: MyWord2 LEFTOVER:
MY WORD: MyThirdWord LEFTOVER: ,        MoreTrash,!##
MY WORD: LastWord LEFTOVER:      x.
```
### Join Genus and species names
```
STRING: 
Lasius neoniger
Lasius umbratus
Myrmica lobifrons
SEARCH: (\w)\w+ (\w+)
REPLACE: \1_\2
RESULT:
L_neoniger
L_umbratus
M_lobifrons
```
### Custom character sets

```
[ATCG] # single character that is A T C or G
[ATCG]+ # DNA sequence
```
### Negated character sets
```
[^XY]  # a single character that is anything but X OR Y
[^0-9.]+ one or more characters that are not numbers of decimals
```
### Boundary stakes
```
^ # outside of character set indicates start of line
$ # indicates end of line
- `\<` Start of a word (but not in BBedit)
- `\>` End of a word (but not in BBedit)
```

### E11: Search for whole words within regex

```
STRING:
Try to ascertain a kind of karma.
SEARCH:
a
RESULT: finds 5 matches

Search:
a 
RESULT: finds 1 match (whole word)

Search:
a\w
RESULT: finds 1 match (start of word)

Search:
\wa
RESULT: finds 1 match (end of word)

Search:
\wa\w
RESULT: finds 2 matches (middle of word)
```



### E12: Simplify column searches by staking to the beginning or end of the line



```
STRING:
a,b,c,d,e,f,MyFirstWord,g,MyLastWord
ee,f,FirstKeeper,xx,LastKeeper
SEARCH:
\w+,\w+,\w+$
SEARCH (with capture):
(\w+),\w+,(\w+)$
REPLACE:
\1 \2
RESULT:
a,b,c,d,e,f,MyFirstWord MyLastWord
ee,f,FirstKeeper LastKeeper
# Perhaps not exactly what we wanted!

ALTERNATE SEARCH: 
.*,\w+,\w+,\w+$
ALTERNATE SEARCH: (with capture):
(.*),(\w+),(\w+),(\w+)$
REPLACE:
\2\s\4
RESULT:
MyFirstWord MyLastWord
FirstKeeper LastKeeper

ALTERNATIVE REPLACE:
\1,\2
ALTERNATIVE RESULT:
a,b,c,d,e,f,g
ee,f,xx
```

### Finding bad characters
```
STRING: 
LC1 11101 xxx
LC345 11101 204
LCx 11l01 1x5
SEARCH: ^(\w+) \d*([^0-9]*)\d* \w+$
RESULT:
LC1
LC345
LCx l
Finds "bad" lines with non-numeric characters in second slot
```
