---
title: 'Lecture #1: Using GitHub'
author: "Nicholas J. Gotelli"
date: "January 17, 2018"
output:
  html_document:
    highlight: tango
    keep_md: yes
    theme: united
  pdf_document: default
---

___

#### Traditional and Modern Computational Tools
- Traditional
    + Word/Excel/Powerpoint
    + SAS/SPSS/JMP for stats
    + Sigmaplot

- Commercial
- Proprietary

- Expensive, availability of updates
- Code not available to modify, improve
- File formats usually not compatable
- Poor tools for documentation, transparency

- Modern
    + LaTeX/Markdown/Typora/Overleaf (instead of Word)
    + plain-text editors (instead of Excel)
    + Beamer slides (instead of Powerpoint)
    + R (instead of stats and graphics packages)
    
- Advantages of Modern
    + free, open source
    + files always usable and readable
    + huge network of expert users (Wikipedia style)
    + less vulnerable to hackers and malware
    
- Learning to code
    + deeper understanding of problem
    + hypothesis testing
    + life long habit of learning and staying abreast of field
    
#### Thinking On Paper
- the logic tree (the basis for "strong inference" that is rarely used explicitly)
- the look-up table (organize the results of multiple statistical analyses with a "dip-switch" test)
- the path diagram (for specifying variables and being explicit about cause-and-effect)
- the simulated data analysis (complete all of your statistical analyses and know how you will interpret the results before your experiment is even finished)


#### Computational Tools
- Git and GitHub (for tracking and documenting your work)
- RMarkdown (to easily build webpages and pdfs with or without R code)
- Beamer (pdf slides that blow away Powerpoint presentations)
- Regular Expressions (find-and-replace on steroids)
- LaTeX (for type-setting equations and improving your slides)
- learning new tools (how to learn how to do things in R)

#### Programming Skills
- Basic coding in R studio (functions, scripts, sourcing, console)
- Foundational Programming Methods (annotating code, for loops, control structures, ifelse, and much more) 
- Data Files (creating and annotating your data files for safe storage and archival use)
- Stochastic Modeling (using random sampling to add realism to models)
- Null Models (simple permutation tests for estimating *p*-values)
- Markov Models (transition matrices for population growth, succession, climate change and more)

#### Experimental Designs
- Graphics (creating publication quality graphics with `ggplot2()`)
- Basic experimental designs (ANOVA, regression, logistic regression, contingency table)
- Data simulation (normal, uniform, poisson, beta, gamma distributions)

### Basic Vocabulary
- `Version Control` A system for maintaining current and past copies of all of your files and a record of all the changes you have made
- `git` Version control software for tracking your project on your local computer
- `GitHub` A free, public remote website where your project is permanently hosted
- `Repository` Any collection of files that belong to the same project, plus a few special `git` files that set up the version control. Also called a `repo` by hipster programmers.
- `Clone` Create a local copy of a repository from the GitHub website to your own website. You can clone from your own repository or anyone else's that is posted on GitHub. Once the files are on your local computer you can edit or use them as you like. However, you can only change files on GitHub for the repositories that you yourself created or for projects that you have been invited to collaborate on with others.
- `Commit (the noun)` A snapshot of your file system at a particular time. Since your last commit, it keeps track of the files you currently have, the ones you have deleted or added, and any changes you have made to files.
- `Commit (the verb)` When you commit, you are taking a snapshot of your files at the current time. You must add a summary of the commit that briefly describes what changes you have made (such as "Added new homework file"). Note that all commits affect only the local copy of your repository. They do not affect the remote copy that is stored on GitHub
- `Push` Pushing a set of changes means copying them from your local repository up to GitHub.
- `Pull` Pulling means copying the repository in its current state on GitHub down to your local repository. This would incorporate any changes that others have made (and pushed) in a collaborative project.
- `Sync` The GitHub desktop software combines pushing and pulling into a single operation. At the end of a sync, the copy of your local repository is identical to what is on GitHub. Syncing also updates your webpages that are associated with the project with any changes that you have made to the `.html` pages.  

### Create An RStudio Project
- In R Studio under `File` select `New Project`
- Select `New Directory` and then `Empty Project`
- Use the menu to set the directory and the project name
- Make sure the `git repository` box is checked
- Open the `gitignore` file and add a line with `*.Rproj` 

### Set Up The Primary Index File
- From the pulldown menu below `File` choose `R Markdown`^[To create a fancier webpage, select `From Template` and then `Lightweight and Pretty Document (HTML)`. This template will produce nicer looking html pages, especially for the initial header and for the display of tables. However, these templates can be rendered only to `.html`. If you want to be able to render to `.html`, `.pdf`, or `.docx` files, then stick with the initial `R Markdown` choice.]
- Keep the Default Output Format as `HTML`
- Add a title such as `Homepage`
- Save this initial file with the name `index`. RStudio will automatically add the required file suffix `index.Rmd`
- Use `CTRL-SHIFT-K` to knit this `index.Rmd` file and create `index.html`'. This is the portal website that will be created through GitHub
- Delete the template text, but retain the initial `yaml` lines down through the second set of dashes `---`
- Add text to the webpage such as `Initial website for GitHub project`
- Go to the `Settings` icon and select `Output Options`. Choose from the different `Syntax highlighting` and `Themes` options and then knit the file to see how it changes the appearance of the `html`^[NJG prefers `tango` for syntax highlighting and `united` for the theme. Instead of using the menu, you can directly type in your choices by hand into the yaml section at the top. If you enter a choice that is not on the menu list, it will generate an error and fail to knit, but you will also see from the error message that there are additional themes and styles that are not on the menu (yet). Explore!]

### Host The New Project At GitHub
- Open `GitHub Desktop`
- From the upper-left pulldown menu, choose `Add Project`
- Select the Rmarkdown project folder that created
- Add text to the summary box such as `Initial project commit`. 
- Click on the `Commit to master` circle to make the commit.
- Notice the diagram indicating the current state of the repository (open circle) and the past commit (closed circles). Each time you make a commit, another circle will be added to the line.

### Publish Your Initial Webpage
- Click on the `Publish` button. Note that this button will appear only once, when you first set up your repository.
- Provide a short description of the project in the indicated box
- Use the `Sync` button to synchronize the local copy of the repository on your computer with the repository that is permanently hosted at GitHub. When you sync your project, any changes that you have made locally are "pushed" up to GitHub, and any changes that others may have made to the repository (in a collaborative project) are "pulled" down from GitHub to your local repository. At the end of the sync, your local copy of the Repository is identical to the one on GitHub.
- Click on the options icon to view the repository on your GitHub page
- log in to GitHub, using the username and password you chose when you set up your account
- go to the new repository and choose settings, then scroll down to `GitHub Pages`
- Choose `Master Branch` and save
- Click on the website http link, which will have this form: `http://USERNAME.github.io/PROJECTNAME/`
- you will probably want to bookmark this page^[Be patient because it can take a few minutes for GitHub to load or to update your webpage.]


### Add A ReadMe and License To Your Repository
- Click on the button to add a `ReadMe` file. This will open up a text box that has the description you entered. Add a carriage return or some other change to the text to activate it, and then save it
- Click on the `Preview` tab to see what it will look like on your GitHub page
- At the bottom of the page add your summary (such as "Added Readme File" and make your commit
- Click on `add new file` and select a license (GNU or MIT is fine)
at the bottom of the page add your summary (such as "Added License") and make your commit^[As the license explains, its purpose is to make sure the materials and code you post on GitHub remain public and free, and prevents anyone else from using and then patenting them!]
- Note that the two changes you have made to your repository were done on the GitHub. Therefore, the local copy of the repository on your computer does not yet have these new files.

### Synching changes locally
- Return to your Desktop GitHub and sync with the remote
- Use the file explorer or the file list in RStudio. Notice that the new readme and license files now show up and the commits are added to your commit history
- You are now ready to do some work on your new webpage(s)

### Typical workflow
- Add new files and links to your original index page 
- Delete old files and change existing files  
- Within your folder project, you can create folders for organizing all of your new pages and scripts. To make a link to these from your index page, the markdown format is  [DisplayText](FolderName/FileName.html)
- When you make changes to .Rmd files, make sure you knit them (CTRL-SHIFT-K) so that a new version of the html is created
- After finishing a logical chunk of work, go to GitHub Desktop, and you will see that changes are indicated in the current state of the repository
- Write a short summary to describe the changes you have made and then commit them. Note that the commit affects only the local copy of your repo
- Now hit synchronize, which will "push" your changes up to the remote GitHub site and update your webpage
- The sync button will also pull down to your local copy any other changes that have been made to the repo that have been incorporated into the remote site. This is only relevant if you are collaborating with others and multiple people are making changes to a repo 

### Dealing with a coding disaster
- If you cannot fix your R code, make a commit and indicate that this is a botched set of files
- Hit the revert button, which makes a new commit that reverts the changes from this commit
- To be safe, do this only for your most recent commit in the history
- Now you will have lost all of your work since that last commit, but at least everything will work now
- For this reason, it is smart to make commits frequently, each time you complete a little chunk of something and it works

### Permanently Deleting A Repository From GitHub
- When you first get started with GitHub, it pays to practice a bit with a fake repository, and then delete it after you have played with it and tried out different operations 
- Do this as often as you need to get comfortable with setting up a repository, building an `index.html` home page, adding a site license and readme file, publishing your webpage, making changes, commiting those changes and describing them with a simple summary statement, and syncing your local repository with the remote
- To permanently remove a repository, go to `Settings` on the repository page on GitHub
- Scroll down to the "red" section to delete the repository
- GitHub forces you to type in the name of repository before destroying it because it can never be recovered
- Note that the local copy of this repository on your computer is NOT destroyed, just the master copy on the remote. You still have those files if you want to move them into a new repository. But you should not move the `.git` or `gitignore` files because those will be created when you set up a new repository 
