---
title: 'Lecture #7: Atomic Vectors & Subsetting'
author: "Nicholas J. Gotelli"
date: "February 6, 2018"
output:
  html_document:
    highlight: tango
    keep_md: yes
    theme: united
  pdf_document: default
---
#### Using `rep` to repeat elements and create vectors
```{r, eval=FALSE}
# rep for repeating elements
rep(0.5,6) # give the element (or vector!) and number of times to repeat
rep(x=0.5,times=6) # using the argument names is always prudent
rep(times=6,x=0.5) # with argument names, order is not important
myVec <- c(1,2,3)
rep(x=myVec,times=2) # applies to entire vectors
rep(x=myVec,each=2) # repeat each element individually
rep(x=myVec,times=myVec) # what does this do?
rep(x=myVec,each=myVec) # and this?
```

#### Using `seq` to create regular sequences
```{r,eval=FALSE}
seq(from=2, to=4) # set limits for integer sequences
2:4 # very common short cut with no explicit function wrappers
seq(from=2,to=4,by=0.5) # use a by function can generate real numbers
x <- seq(from=2, to=4,length=7) # sometimes easier to just specify the length
myVec <- 1:length(x) # commonly used, but actually slow
print(myVec)
seq_along(myVec) # much faster for models and big data!
seq_len(5) # this is also faster than 1:5
```

#### Using `rnorm` and `runif` to create vectors of random numbers
```{r,eval=FALSE}
runif(5) # 5 random uniform values betweeon 0 and 1
runif(n=3,min=100, max=101) # 3 random uniform values between 100 and 101

rnorm(6) # 6 random normal values with mean 0 and standard deviation 1
rnorm(n=5, mean=100, sd=30) # 5 random normal values with mean 100 and sd 30

## Explore distributions by sampling and plotting
library(ggplot2) # do this at the very start
z <- runif(1000) #default uniform (0,1)
qplot(x=z)
z <- rnorm(1000) #default normal (0,1)
qplot(x=z)
```

#### Using `sample` to draw random values from an existing vector

```{r,eval=FALSE}
longVec <- seq_len(10)
typeof(longVec)
str(longVec)

sample(x=longVec) # with no other params, this reorders the vector
sample(x=longVec, size=3) # specify a number (sampling without replacement)
sample(x=longVec,size=16,replace=TRUE) # can generate duplicates
myWeights <- c(rep(20,5),rep(100,5)) # create a set of non-zero positive weights (integer or real)
print(myWeights)
sample(x=longVec,replace=TRUE,prob=myWeights) # sampling with replacement and weights
sample(x=longVec,replace=FALSE,prob=myWeights) # sampling without replacement and weights
sample(x=longVec,replace=TRUE,prob=longVec) # what does this do?
```


### Techniques for subsetting atomic vectors

```{r,eval=FALSE}
z <- c(3.1, 9.2, 1.3, 0.4, 7.5)

# positive index values
z[c(2,3)]

# negative index values to exclude elements
z[-c(2,3)]

# create a vector of logical elements to select conditions

z[z<3]

# equivalent to the following
tester <- z<3
print(tester)
z[tester]

# also use which() function to find subscript indicators
which(z<3)

# this works the same for most vectors
z[which(z<3)]

# but note this difference with NA values

zMiss <- c(NA,z)

#simple subscripting includes NA values!
zMiss[zMiss<3]

# which function excludes NA values!
zMiss[which(zMiss<3)]

# can also use length() for relative positioning to last element
z[-(length(z):(length(z)-2))]

# also can subset using named vector elements
names(z) <- letters[1:5]
z[c("b","c")]


```

### Arithmetic Operators

```{r, eval=FALSE}
10 + 3
10 - 3
10 * 3
10 / 3
10^3
10^0.5
log(10)
log10(10)

# modulus operator (remainder)
10 %% 3

# get the set of all numbers from 1 to 100 divisible by 9

q <- seq_len(100) # generates 1:100
q[q%%9==0]

# integer division
10%/% 3
```

### Relational Operators

```{r,eval=FALSE}
# These will all return a boolean
3 < 4
3 > 3
3 >= 3
3 <= 4
3 == 4  # but not 3 = 4
3 != 4  # NOT equal


```

### Set Operators
```{r,eval=FALSE}
# compares two atomic vectors and returns an atomic vector
# setequal, is.element, and %in% return a single boolean
# always strips out duplicate elements before operations
i <- c(1,1:7)
print(i)
j <- c(3:10)
print(j)

union(i,j) # all elements
intersect(i,j) # common elements
intersect(i,11) # this yields an empty set
setdiff(i,j) # unique elements of i that are not in j
setdiff(j,i) # unique elements of j that are not in i
setequal(i,j) # returns a boolean
setequal(i,i)
is.element(i,j) # compare elements in i to those in j
is.element(j,i) # compare elements in j to those in i
i %in% j #equivalent to is.element(i,j)
```

### Logical operators

```{r, eval=FALSE}
z <- 10:20
z < 15
z < 20 & z > 17 # element by element AND
# use && for just first element comparison

z < 20 | z > 17 # element by element OR
# use || for just first element comparison

! 5 # NOT coerces values to logical first 
! 0
! TRUE #not negates TRUE FALSE (real values coerced)
any(z<15) # returns a single TRUE  if any element matches
all(z<15) # returns a single true if all elements match
all(z<21 | z > 9) # note inner calculation of boolean vector

m <- 1:5
n <- c(0,9,3,4,5)
xor(m,n) # exclusive element wise or: one must be true, other false
xor(1,0)
```


