---
title: "Lecture Outlines"
author: "Biology 381 - Computational Biology"
date: "Spring 2018"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

## Lecture Schedule

Date  | Lecture | Topic
------------- | -------------- |-----------
January 16 | 01  | [GitHub](Lecture01.html) 
January 18 | 02 | [Thinking On Paper](Lecture02.html) 
January 23 | 03 | [RStudio](Lecture03_4.html) 
January 25 | 04 | [RStudio II](Lecture03_4.html) 
January 30 | 05 | [Beamer Slides](Lecture05.html) 
February 1 | 06  | [Importing Data](Lecture06.html) 
February 6 | 07  | [Regular Expressions](Lecture07_8.html) 
February 8 | 08 | [Regular Expressions II](Lecture07_8.html)
February 13 | 09 | [Atomic Vectors](Lecture09.html)
February 15 | 10 | [Data Structures](Lecture10.html)
February 20 | 11 | [Subsetting](Lecture11.html)
February 22 | 12| [Probability Distributions](Lecture12_13.html)
February 27 | 13   | [Probability Distributions II](Lecture12_13.html)
March 1 | 14  | [Functions](Lecture14.html)
March 6 |  -  | *TOWN MEETING DAY RECESS* 
March 8 | 15  | [Structured Programming](Lecture15.html)
March 13 | -  | *SPRING RECESS* 
March 15 | -  | *SPRING RECESS* 
March 20 | -  | TBA
March 22 | -  | *NO CLASS*
March 27 | 16  | [Control Structures](Lecture16.html) 
March 29 | 17  | [Control Structures II](Lecture17.html) 
April 3 | 18  | [Control Structures III](Lecture18.html) 
April 5 | 19  | [Control Structures IV](Lecture19.html) 
April 10 | 20  | [Randomization Tests](Lecture20.html) 
April 12 | 21  | [Markov Models](Lecture21.html) 
April 17 | 22  | [Markov Models II](Lecture22.html) 
April 19 | 23  | [Apply Functions](Lecture23.html) 
April 24 | 24  | [Base Graphics I](Lecture24.html) 
April 26 | 25  | [Base Graphics II](Lecture24.html) 
May 1  | **Research Presentations [4]** |
May 3  | **Research Presentations [4]** |
