---
title: 'Lecture #2: Thinking On Paper'
author: "Nicholas J. Gotelli"
date: "January 18, 2018"
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---

___

### Advantages of Paper Notebooks
- portable
- fast
- use in public (dull seminars, useless meetings)
- used in good teaching (lecture, office hours)
- the way of science
- can be beautiful and permanent or ugly and temporary

### My Notebooks
- Leuchtrum
- tiny pocket notebook for travel
- Engineering pad of graph paper for teaching
- green legal paper for office hours

### Philosophy of Science
- Francis Bacon and Deductive Method
- Karl Popper and Hypothetico-deductive Method
- JR Platt 1964 Strong Inference

### Fuzzy Thinking in Ecology
- complex, interacting factors
- a mix of abiotic, biotic, and historical forces
- Tangled-Bank Fever
- Fuzzy wording
- The importance of process x on pattern y
    - The relative importance of factors w, x, and y on pattern z
    - The implications of x for y
    - The interaction of x and y

### Building Hypotheses On Paper

How to sketch out ideas and make questions and analyses clear

#### Path Diagram (Cause-And-Effect Flow Chart)
- circle represents a variable or something we can measure
- arrow links two variables in a cause and effect relationship
- reciprocal arrows for reciprocal effects
- single headed arrows for self regulation
- latent variables for unmeasured things
- used in path analysis
    - often just a single path diagram with significance tests for links
    - better to compare whole pathways
    - test for latent variables (not measured)
- a particular path structure is a distinct hypothesis
- what unique predictions does it make?
- example: Gotelli & Ellison (2006) Sarracenia Food Webs

#### Logic Tree (Branching Decision Tree)
- Each fork represents a decision, framed as a question
- branches below the fork are possible answers (usually 2, but may be more)
- each branch is labelled with an "answer" to the question (usually yes/no but other choices are possible)
- two possible end points for a branch
    * an additional lower branch
    * a terminal inference of mechanism or interpretation of pattern
- branching pattern need not be symmetrical
- some branches could point to a single outcome
- a single outcome could have more than one interpretation (i.e.,incomplete data)
- a priori tree to interpret ongoing experiments (difficult and rare, but highly desirable)
- post hoc tree to organize and interpret different tests (easier, but also rare)
- example: Gotelli et al. (in review) Community-Level Regulation

#### Look-Up Table (DIP-Switch Test For Multiple Tests)
- Rosenzweig and Abramsky (1997) refers to Dual InLine Package Switch
- Each column represents a different (statistical) test or comparison
- Each row represents a unique outcome based on all of the tests
- 3 tests corresponds to 8 outcomes = 1 byte of length 3 bits (most computer bytes are 8 or 16 bits) 
- Each test outcome corresponds to a number (0,7) in binary base 2
- Entries in the table are usually dichotomous (no, yes or + -)
- Each entry may correspond to a terminal branch tip in the logic tree
- Final column of the Look-Up Table is a named hypothesis or interpretation
- As in the logic tree, some rows may yield the same interpretation (i.e., incomplete data)
- example: Chase et al. (in prep) MoB Measurement of Biodiversity Data

#### Mock Data (Predicted versus Observed Outcome Graphs)
- Simple statistical null hypothesis (i.e., no effect) usually not interesting
- Choose a single hypothesis, possibly a more "interesting" null hypothesis
- Outcomes correspond to a row of the Look-Up Table or a branch tip in the Logic Tree
- Create graph for observed data AND for expected data for the hypothesis
- Most useful for 3 or more pattern tests
- Next step: simulate data to match your experiment
    - ultimate a-priori predictions
    - illustrates whether your replication and design has any power
    - leads to question of realistic effect sizes
    - apocryphal Schoener dissertation study
- example: Diamond et al. (2016) Climate Warming Destabilizes Forest Ant Communities 

### Problems
- Study may be just figuring out initial patterns
- Hypotheses not clearly stated in the literature (but  you can do better!)
- Hypotheses may seem too humble or trivial (still worth doing)
- All good reasons for trying it!
