---
title: 'Lecture #12: Probability Distributions II'
author: "Nicholas J. Gotelli"
date: "October 4, 2018"
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

#### Poisson distribution

```{r, eval=TRUE}
library(ggplot2)
#-------------------------------------------------
# Poisson distribution
# Discrete X >= 0
# Random events with a constant rate lambda
# (observations per time or per unit area)
# Parameter lambda > 0

# "d" function generates probability density
hits <- 0:10
myVec <- dpois(x=hits,lambda=1)
qplot(x=hits,y=myVec,geom="col")

myVec <- dpois(x=hits,lambda=2)
qplot(x=hits,y=myVec,geom="col")

hits <- 0:15
myVec <- dpois(x=hits,lambda=6)
qplot(x=hits,y=myVec,geom="col")


hits <- 0:15
myVec <- dpois(x=hits,lambda=0.2)
qplot(x=hits,y=myVec,geom="col")

sum(myVec)  # sum of density function = 1.0 (total area under curve)

# for a Poisson distribution with lambda=2, 
# what is the probability that a single draw will yield X=0?

dpois(x=0,lambda=2)

# "p" function generates cumulative probability density; gives the 
# "lower tail" cumulative area of the distribution

hits <- 0:10
myVec <- ppois(q=hits,lambda=2)
qplot(x=hits,y=myVec,geom="col")


# for a Poisson distribution with lambda=2, 
# what is the probability that a single random draw will yield X <= 1?

ppois(q=1, lambda=2)


# We could also get this through dpois
p1 <- dpois(x=0,lambda=2)
p1
p2 <- dpois(x=1,lambda=2)
p2
p1 + p2


# The q function is the inverse of p
# What is the number of hits corresponding to 50% of the probability mass
qpois(p=0.5,lambda=2.5)
qplot(x=0:10,y=dpois(x=0:10,lambda=2.5),geom="col")

# but distribution is discrete, so this is not exact
ppois(q=2,lambda=2.5)

# finally, we can simulate individual values from a poisson
ranPois <- rpois(n=1000,lambda=2.5)
qplot(x=ranPois)


# for real or simulated data, we can use the quantile
# function to find the empirical  95% confidence interval on the data

quantile(x=ranPois,probs=c(0.025,0.975))
```

#### Binomial distribution

```{r, eval=TRUE}
#-------------------------------------------------
# Binomial distribution
# p = probability of a dichotomous outcome
# size = number of trials
# x = possible outcomes
# outcome x is bounded between 0 and number of trials

# use "d" binom for density function
hits <- 0:10
myVec <- dbinom(x=hits,size=10,prob=0.5)
qplot(x=0:10,y=myVec,geom="col")

# what is probability of getting 5 heads out of 10 tosses?
dbinom(x=5,size=10,prob=0.5)

# of course, the coin can be a biased one
myVec <- dbinom(x=hits,size=10,prob=0.95)
qplot(x=0:10,y=myVec,geom="col")

# use "p" binom for cumulative distribution


# what is the probability of getting 5 
# or fewer heads out of 10 tosses?
pbinom(q=5,size=10,prob=0.5)
pbinom(q=4,size=9,prob=0.5)



# what is a 95% confidence interval for 100 trials 
# of a coin with p = 0.7 for heads?
qbinom(p=c(0.025,0.975),size=100,prob=0.7)

# and how does this compare to the interval for an actual simlation of 50 tosses of 100 coins?

myCoins <- rbinom(n=50,size=100,prob=0.5)
qplot(x=myCoins)
quantile(x=myCoins,probs=c(0.025,0.975))

```

#### Negative Binomial distribution

```{r, eval=TRUE}
#-------------------------------------------------
# negative binomial: number of failures (values of MyVec)
# in a series of (Bernouli) with p=probability of success 
# before a target number of successes (= size)
# generates a discrete distribution that is more 
# heterogeneous ("overdispersed") than Poisson
hits <- 0:40
myVec <- dnbinom(x=hits, size=5, prob=0.5)
qplot(x=hits,y=myVec,geom="col")

# geometric series is a special case where N= 1 success
# each bar is a constant fraction 1 - "prob" of the bar before it
myVec <- dnbinom(x=hits, size=1, prob=0.1)
qplot(x=hits,y=myVec,geom="col")


# alternatively specify mean = mu of distribution and size, 
# the dispersion parameter (small is more dispersed)
# this gives us a poisson with a lambda value that varies
# the dispersion parameter is the shape parameter in the gamma
# as it increases, the distribution has a smaller variance

MyVec <- dnbinom(x=seq(0,40),size=1,mu=5)
names(MyVec) <- seq(0,40)
barplot(height=MyVec)


# also have the "pnbinom", "qnbinom" and "rnbinom" functions
# Probability of drawing a 3 or smaller from a negative binomial:
pnbinom(q=3,size=1,mu=5)

# 5 percent lower value for a negative binomial
qnbinom(p=0.05,size=10,mu=5)

# 95% confidence interval for a geometric series
qnbinom(p=c(0.025,0.975),prob=0.5,size=10)

# random sample from a negative binomial

MyVec <- rnbinom(n=1000,size=1,mu=20)
quantile(MyVec,prob=c(0.025,0.975))

# compare to exact calculation
qnbinom(p=c(0.025,0.975),size=1,mu=20)
```

#### Uniform distribution

```{r}
#-------------------------------------------------
# uniform
# params specific minimum and maximum

# dunif for density plot
limits <- seq(0,10,by=0.01)
z <-dunif(x=limits,min=0,max=5)
names(z) <- limits
plot(x=limits, y=z,type="l",xlim=c(0,10))

#punif for cumulative density (= tail probabilities)
limits <- seq(0,10,by=0.01)
z <-punif(q=limits,min=0,max=5)
names(z) <- limits
plot(x=limits, y=z,type="l",xlim=c(0,10))

#qunif for quantiles
qunif(p=c(0.025,0.975),min=0,max=5)

#runif for random data
hist(runif(n=100,min=0,max=5))
hist(runif(n=1000,min=0,max=5))
#-------------------------------------------------
```
#### Normal distribution

```{r}
# normal 

hist(rnorm(n=100,mean=100,sd=2))

# problems with uniform when mean is small but zero is not allowed.
hist(rnorm(n=100,mean=2,sd=2))
MyVec <- rnorm(n=100,mean=2, sd=2)
summary(MyVec)
TossZeroes <- MyVec[MyVec>0]
hist(TossZeroes)
summary(TossZeroes)
```

#### Gamma distribution

``` {r}
#-------------------------------------------------
# gamma distribution, continuous positive values, but bounded at 0

hist(rgamma(n=100,shape=1,scale=10))

# gamma with shape= 1 is an exponential with scale = mean

# shape <=1 gives a mode near zero; very small shape rounds to zero
hist(rgamma(n=100,shape=0.1,scale=1))

# large shape parameters moves towards a normal
hist(rgamma(n=100,shape=20,scale=1))

# scale parameter changes mean- and the variance!

hist(rgamma(n=100,shape=2,scale=10))
hist(rgamma(n=100,shape=2,scale=100))
hist(rgamma(n=100,shape=2,scale=1))
hist(rgamma(n=100,shape=2,scale=0.1))

# unlike the normal, the two parameters affect both mean and variance

# mean = shape*scale
# variance= shape*scale^2
```

#### Beta distribution 

```{r}
#-------------------------------------------------

# beta distribution 
# bounded at 0 and 1
# analagous to a binomial, but result is a continuous distribution of probabilities
# parameter shape1 = number of successes + 1
# parameter shape2 = number of failures + 1
# interpret these in terms of a coin you are tossing

# shape1 = 1, shape2 = 1 = "no data"
hist(rbeta(n=1000,shape1=1,shape2=1),breaks=seq(0,1.0,length=100))

# shape1 = 2, shape1 = 1 = "1 coin toss, comes up heads!"
hist(rbeta(n=1000,shape1=2,shape2=1),breaks=seq(0,1.0,length=100))
hist(rbeta(n=1000,shape1=1,shape2=2),breaks=seq(0,1.0,length=100))

# two tosses, 1 head and 1 tail
hist(rbeta(n=1000,shape1=2,shape2=2),breaks=seq(0,1.0,length=100))

# two tosses, both heads
hist(rbeta(n=1000,shape1=3,shape2=1),breaks=seq(0,1.0,length=100))

# let's get more data
hist(rbeta(n=1000,shape1=20,shape2=20),breaks=seq(0,1.0,length=100))

hist(rbeta(n=1000,shape1=500,shape2=500),breaks=seq(0,1.0,length=100))

# if the coin is biased
hist(rbeta(n=1000,shape1=1000,shape2=500),breaks=seq(0,1.0,length=100))
hist(rbeta(n=1000,shape1=10,shape2=5),breaks=seq(0,1.0,length=100))


# shape parameters less than 1.0 give us a u-shaped distribution
hist(rbeta(n=1000,shape1=0.1,shape2=0.1),breaks=seq(0,1.0,length=100))
hist(rbeta(n=1000,shape1=0.5,shape2=0.5),breaks=seq(0,1.0,length=100))
hist(rbeta(n=1000,shape1=0.5,shape2=0.2),breaks=seq(0,1.0,length=100))
```

### Estimating paramaters from data

```{r}
#-------------------------------------------------
# estimating parameters from data
# maximum likelihood estimator theta versus P(data|theta)

# use fitdistr function, feeding it data and a distribution type)
library(MASS)
x <- rnorm(1000,mean=92.5,sd=2.5)
hist(x)
fitdistr(x,"normal")

# compare to true parameters
# compare to parameters estimated from simple means and standard deviations
mean(x)
sd(x)

# but how do we "know" what distribution to fit?
fitdistr(x,"gamma")
z <- fitdistr(x,"gamma")

# find components of z
str(z)
# rate = 1/scale
# so here is the estimate of the mean
z$estimate[1]/z$estimate[2]

# and here is the estimate of the variance
z$estimate[1]/z$estimate[2]^2
```
