---
title: 'Homework #2'
author: "Nicholas J. Gotelli"
date: "September 5, 2018"
output: 
  html_document: 
    highlight: tango
    theme: united
---


1. Take a broad, self-critical look at your entire thesis/honors project. What are the big questions you are asking, and what are the specific hypotheses and mechanisms that your experiments and sampling are trying to address? How will you interpret the different possible results from your activities? Be explicit and detailed; do not hide behind jargon or vague statements.  

2. Translate your answers to these questions into any 2 of the 4 diagrams we discussed in class: a) cause-and-effect diagram; b) pre-graph; c) DIPSwitch table c) logic tree. You may have to try several versions to get a satisfying result.

3. Lauren will illustrate a simple programmming language embedded within Typora that will allow you to create a flowchart diagram of your figure. Alternatively, you could also make a neat pen and ink drawing of your figure, photograph it with your iphone, and send it to your computer.

4. After an hour or devoted to working on these diagrams, Lauren will ask you to volunteer to bring your diagram up to the overhead projector. Show it to the class, and explain the mechanisms and links you are working with. The class should ask questions and give you feedback for improving the figure.

5. At your index page, build a link to a page called `Homework02`.

6. Create `Homework02.Rmd` as a new Markdown file.

7. Insert each of the images into the file and compile as an `.html`.

8. Use GitHub to make frequent commits, and sync your repo to update your webpages.

9. Add Markdown titles, formatting, and text, and develop a narrative to explain each figure, the hypotheses they elaborate, and the expected outcomes of your experiments and observations. If you hit a wall in developing your hypotheses, try to write some text explaining what the issues are. 

10. As your project progresses, you may want to return to this webpage to update (and hopefully improve!) your diagrams and interpretations.

### Building a Flowchart in Typora

1. In Typora, go to `preferences` (under the `file` or `edit` pull-down menu) and check the `Diagrams` option.

2. In Typora help, go to `More Topics...` and `Draw Diagrams With Markdown`

3. Scroll down to `Flowchart` and copy the code snippet into a fresh Typora file.

4. Click outside the box and you should see this code rendered as a nice flow chart.

5. Now study the code to understand how it works, and then modify it to recreate your flow chart or logic tree diagram from last week. 

6. Add some text and pick a nice theme, and then render the Typora `.md` file to `.html` and push the changes to your repo.
