---
title: 'Homework #9'
author: "Nicholas J. Gotelli"
date: 'March 15, 2017'
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---

We now have learned the tools for you to begin analyzing and plotting your data, and seeing how your model performs on some random data.

1. Create a new markdown file and import the data set that you created in Homework #4.

2. Using (and possibly modifying) some of the functions you created last week in Homework #8, carry out some basic analyses of your data. For this exercise, it is not necessary to fit fancy or complex ANOVA models (although you certainly can do so if you are already at that stage). You can fit basic models by simply ignoring some of the factors (such as time or subsample) in your design.

3. Be sure you set up your analysis so that you call data into your functions like this `fitReg(myData)`.


4. Do the same thing to create basic plots of your data. If you already know how to work with some of R's graphics parameters (through the `plot` or `par` functions), go ahead and modify your functions to spiff up your graphs.

5. Next, build some functions to construct a random data set `randomData` that has the same structure as your original data. Use `dgamma` to simulate continuous variables that are > 0. If you have any integer variables try simulating them with `rpois` or `rnbinom`. Use the parts of your original data frame that specify the factors, plots, and replicates. In this way you will preserve the sample size and structure of your original data set.

6. You will need to choose parameters (such as `shape` and `scale` for the gamma) that seem realistic and appropriate for your data. In your markdown narrative, explain how you arrived at these choices, and illustrate a couple of "experiments" by generating a set of random values as you tinker with your parameters. You should calculate the mean and variance of any simulated data set to make sure it gives you something realistic. You may want to compare with some published values from the literature. You could also try using `fitdistr` on parts of your data 
as a starting point for parameters.

7. Next, add code to recreate your analyses, this time using your random data set. Thus, if you used `fitReg(myData)` to analyze your real data, now you would call `fitReg(randomData)` to recreate the analysis using the random data. This kind of analysis really illustrates the power and convenience of setting everything up with functions and then just swapping in other data sets or parameter values.

8. Finally, return to Homework #2, where you sketched out some mechanisms and set up some possible hypotheses for how your data might come out. Use those ideas as a template for creating a new data set, which you should call `randomDataBling`. Here you will need to get in and change means and variances for different groups (or slopes and intercepts in regression analyses) to create the treatment effects. You will also need to give some thought to how large a treatment effect (= difference in means) is realistic and appropriate for your question. Hopefully, you have enough replication to have the statistical power you will need. If not, at least you know that now!

9. Once you have created `randomDataBling`, recreate once more the analyses by calling `fitReg(randomDataBling)` and all of your other functions. To keep things tidy, use just one markdown file with several chunks in it for these three sets of analyses (`myData`, `randomData`, and `randomDataBling`).

