---
title: 'Homework #1'
author: "Nicholas J. Gotelli"
date: "August 29, 2018"
output: 
  html_document: 
    highlight: tango
    theme: united
---


### The workflow for Bio 381

The goal of this first exercise is to get comfortable with the workflow of this course:

* Build a project in Rstudio
* Link your project to a repository that is stored at Github
* Build a webpage `index.html` that is associated with this repository
* Add text, links, and web pages to your repository
* Frequently commit your changes and sync your repo with GitHub
* If your code stops working and you can't repair it, know how to revert changes back to the most recent commit

The detailed instructions for these activities can be found in the notes from [Lecture #1](https://gotellilab.github.io/Bio381/Lectures/Lecture01.html). To get used to the workflow, try the following sequence, creating a project directory on your desktop 

### Exercises and practice for getting comfortable with the workflow
1. Create a project in R studio, and set it up in GitHub with just the index page. Were you able to publish the page? If so, delete the repository on GitHub and delete the local project on your desktop and try it a few more times.

2. Now continue by adding text, and links to your index page. Each page you add should have a commit to store it. Again, when this all works for you, delete the repository and the local project and practice it again.

3. Now that you are getting good at this, try adding a new file and making changes to your index file. Commit those changes and then go to the latest version and use the revert button. Your new file should disappear and the repo should be reset to the previous stage. Again, destroy the repo and the local copy and repeat until you are comfortable with this sequence.

### Building your website for your portfolio

When steps 1 - 3 are very comfortable, it is time to make the repository you will keep and use to build your portfolio of materials for this class. 

* If you use DropBox, set up your Rstudio Project folder inside DropBox. If you do not use DropBox, just put it on your desktop or somewhere else that is convenient^[Using GitHub means you never have to worry about losing your files, even without DropBox. If you ever delete or corrupt the local repository, just throw it away and clone a fresh copy of the repo from GitHub!].

* Name your RStudio project `LastnameBio381`, with no spaces or other characters. For example, if I was building this project for myself, the name would be `Bio381Gotelli`
* All you need to do is to set up your index page with the text "Index page successfully built". We will change that later

### What to turn in
 At the end of the day, email to me (ngotelli@uvm.edu) the following information 
 
* The full website address for your GitHub repository
* The full website address for the homepage of your Bio381 repository
* A one-sentence "fun fact"-- something memorable about you that everyone will always remember when they see you again. Perhaps a famous person you have met, a notable accomplishment, something interesting from your past...
    
Once I have all of this information, I will create a webpage that has links to all of these pages for the entire class. That means you can study the work of others as you do your own coding.    
