---
title: 'Homework #1'
author: "Nicholas J. Gotelli"
date: "January 15 2020"
output: 
  html_document: 
    highlight: tango
    theme: united
---

The goal of this first exercise is to make sure that all of your software is installed properly and to get comfortable with the markdown language.

1. Make sure everything is set up and working on the laptop that you will be using for this course. 

Specifically, you should have the most current versions of R and RStudio installed. Within R, you need the `tinytex` package installed so that can create ("knit") pdf documents.

You also need the latest version of Typora (a markdown editor), a plain text editor (Atom for Macs, or Notepad++ for Windows). And you need to be signed up for a GitHub account and have handy your github user name and password.

Lauren will make a brief presentation and step you through a series of checks to make sure you are ready to go on all of these things.

2. Learn markdown in Typora.

Markdown is a simplified language for plain-text files that uses special symbols to indicate formatting. The plain-text file is then converted ("knit" in RStudio) into a pdf or html document.

Lauren will illustrate for you the basic elements of markdown using the stand-alone Typora editor.

3. Create a typora document to illustrate the following formatting:

* headers (levels 1-6)
* unordered lists
* ordered lists
* manual line breaks
* links
* images
* block quotes
* plain code blocks
* R code blocks
* in line block
* in line LaTeX equation
* centered LaTeX equation
* horizontal rule
* simple table

4. On a piece of paper, draw a simple cause-and-effect diagram to illustrate one or two hypotheses from your research. Circles represent variables or measurements. Arrows (which can be labelled) indicate cause and effect directions.

5. Take a smart phone photo of your flow chart and import the image into your Typora document.

6. Lauren will illustrate simple software for flow charts and diagrams that can be used in Typora. Check out the possibilities at http://support.typora.io/Draw-Diagrams-With-Markdown/

7. See if you can convert your hand-drawn flowchart into one of these display items and imbed it in your Typora document.

8. Try converting your plain-text document to pdf and html and see how they look. Be sure to experiment with the 6 different "themes" that Typora offers. Each theme features a different font and background color.

9. Be sure to save your plaintext document from Typora to your hard drive.


