---
title: 'Homework #11'
author: "Nicholas J. Gotelli"
date: '26 March 2025'
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---

### Strategic Coding Practices
The purpose of today's lab is to use the `upscaler` tools to create the skeleton of a large project and then create some user-defined functions and a MainScript.R to execute everything.

In brief, you will download 10 years of data on breeding land birds. For each yearly data sheet, you will extract abundance and species richness for each year. You will run a simple regression model of S vs. total abundance and write the regression summary statistics to a .csv file. You will also create a histogram, across years, of the abundance and a separate histogram of species richness. Although we haven't covered much detail on ggplot graphics yet, you have enough sample code from previous exercises to create these kind of plots. You will set up a log file, do all of your work with separate user-defined functions, and execute those functions from a single script called MainScript.R. You will store your function files and output files in the appropriate subfolders in your project.

When your work is finished you will compress your entire project folder. In Mac, you can write click on your folder and select the compress option. You may have to do this with a separate application in Windows. This will create a single file called `ProjectName.zip`. Post this single zip file of your entire project to your homework page. In other words, you won't be posting all of the individual files and plots that you create in this exercize, but they will all be contained in the zip file that you will post.
### Batch Processing

###### Data Download 

1. To start, go to this [link](https://data.neonscience.org/data-products/DP1.10003.001) and scroll down to "Download Data". From there, Sort by Site to download the "BART" dataset for years 2013-2023. In this compressed folder, you should see a list of six folders organized by year in the file name. Store that for now somewhere on your desktop.   

From there, follow the instructions from last week's lectures on barracudar functions to create a new project, storing the dataset in a "Original Data" folder. 

2. Within each year's folder, you will only be using a  file from each year labeled "countdata" in its title. Using for loops, iterate through each year's folders to gather the file names of these "countdata" .csv files. 

3. Starting with pseudo-code, generate functions for 1) Cleaning the data for any empty/missing cases, 2) Extract the year from each file name, 3) Calculate Abundance for each year (Total number of individuals found), 4) Calculate Species Richness for each year(Number of unique species found) 

4. Create an initial empty data frame to hold the above summary statistics-you should have 4 columns, one for the file name, one for abundance, one for species richness, and one for year. 

5. Using a for loop, run your created functions as a batch process for each folder, changing the working directory as necessary to read in the correct files, calculating summary statistics with your created functions, and then writing them out into your summary statistics data frame. 


-----------------------------

Use the remainder of the lab period to continue work on Homework 10, if you did not complete it last week:  

2. Use subsetting instead of a loop to rewrite the function as a single line of code.

3. Write a function that takes as input two integers representing the number of rows and columns in a matrix. The output is a matrix of these dimensions in which each element is the product of the row number x the column number.

4. Use the code from the upcoming April 2nd lecture (Randomization Tests) to design and conduct a randomization test for some of your own data. You will need to modify the functions that read in the data, calculate the metric, and randomize the data. Once those are set up, the program should run correctly calling your new functions. Also, to make your analysis fully repeatable, make sure you set the random number seed at the beginning (use either `set.seed()` in base R, or `char2seed` in the `TeachingDemos` package

5. For comparison, calculate in R the standard statistical analysis you would use with these data. How does the p-value compare for the standard test versus the p value you estimated from your randomization test? If the p values seem very different, run the program again with a different starting seed (and/or increase the number of replications in your randomization test). If there are persistent differences in the p value of the standard test versus your randomization, what do you think is responsible for this difference?

--------
