---
title: 'Homework #4'
author: "Nicholas J. Gotelli"
date: "24 February 2021"
output: 
  html_document: 
    highlight: tango
    theme: united
---

### Typora

1. Create a Typora document to illustrate the following formatting:

* headers (levels 1-6)
* unordered lists
* ordered lists
* manual line breaks
* links
* images
* block quotes
* plain code blocks
* R code blocks
* in line blocks
* in line LaTeX equation
* centered LaTeX equation
* horizontal line
* simple table
* text highlighting

2. On a piece of paper, draw a simple cause-and-effect diagram to illustrate one or two hypotheses from your research or from one of your other biology classes. Circles represent variables or measurements. Arrows (which can be labeled) indicate cause and effect directions.

3. Take a smart phone photo of your flow chart and import the image into your Typora document.

4. Lauren will illustrate simple software for flow charts and diagrams that can be used in Typora. Check out the possibilities at http://support.typora.io/Draw-Diagrams-With-Markdown/

5. See if you can convert your hand-drawn flowchart into one of these display items and embed it in your Typora document.

6. Try converting your plain-text document to pdf and html and see how they look. Be sure to experiment with the different "themes" that Typora offers. Each theme features a different font and background color. Follow the links in Typora to the themes pages. Find another theme you like, and then follow the instructions for downloading it and installing it on your computer so that you can use it with Typora.

7. Post the html version of your document to your Github webpage.

### LaTeX

1. Download these two templates for creating letters and slides

[Letter Template](01_UVM_Letter_TEMPLATE.bak)    
[Beamer Template](01_Beamer_TEMPLATE.bak)

2. Open a new `.Rnw` document and copy in the letter template. To get it to run, you will need an image for the letterhead, and an image for your signature. See if you can find a UVM logo online, and also use your phone to take a picture of your own signature.

3. Get the code to run and create your sample letter as a .pdf.

4. Post that pdf with your signature to your Github webpage.

5. Now load the Beamer template and get it to run to create a set of slides.

6. Follow the instructions in the template to try out different themes and fonts, and to insert an image.

7. Do some searching online and see if you can add a caption to an image on a graph. Can you also adjust the positioning and the size? What about two images on a single page.

8. Create your own slide show with maybe 5 or 6 pdf slides by modifying the template.

9. Post the pdf of your new slide show to your Github webpage.



