---
title: 'Homework #9'
author: "Nicholas J. Gotelli"
date: '29 March 2023'
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---

### Organizing Code With Structured Programming

1. Use the code that you worked on in Homework #7 (creating fake data sets), and re-organize it following the principles of structured programming. Do all the work in a single chunk in your R markdown file, just as if you were writing a single R script. Start with all of your annotated functions, preliminary calls, and global variables. The program body should be only a few lines of code that call the appropriate functions and run them in the correct order. Make sure that the output from one function serves as the input to the next. You can either daisy-chain the functions or write separate lines of code to hold elements in temporary variables and pass them along.

2. Once your code is up and working, modify your program to do something else: record a new summary variable, code a new statistical analysis, or create a different set of random variables or output graph. Do not rewrite any of your existing functions. Instead, copy them, rename them, and then modify them to do new things. Once your new functions are written, add some more lines of program code, calling a mixture of your previous functions and your new functions to get the job done.

3. Optional. If time permits and you have the skills, try putting your program inside of a for loop and repeat the analysis with a different stochastic data set (each time you call a function that invokes the random number generator, it will create a new set of data for you to process). Can you create a data structure to store the summary statistics created in each pass through the loop? If not, your program will work, but it will only show the results from the final replicate (the previous results will be written over each time you traverse the loop).

-----
[Structured Programming I Lecture Notes](https://gotellilab.github.io/Bio381/Lectures/Lecture14_S2021.html)    
[Structured Programming II Lecture Notes](https://gotellilab.github.io/Bio381/Lectures/Lecture15_S2021.html)

