---
title: 'Homework #6'
author: "Nicholas J. Gotelli"
date: 'February 22, 2017'
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---

A great resource for R programming is 

> Wickham, H. 2015. Advanced R. CRC Press.

Fortunately, the book is available both as an expensive paperback, but also as a free on-line version at the companion [website](http://adv-r.had.co.nz/). Chapter 4 of Hadley's book gives a core "vocabulary" of essential R functions. I have subsetted that list to include the most important ones that you should learn first.

This week's exercise will be to have the class collectively write some explanation and short sample code illustrating these functions.  There are 143 functions on this list, which coincidentally works out to 13 different functions for each of the 11 students in the class. You will work on your 13, but we will eventually combine all of the results. When you have finished this exercise, I will collate and combine everyone's text and provide a common webpage that can serve as a resource for your programming.

1. Create a new markdown file and a new chunk of R code. Copy and paste the following R code into the chunk, and run it.

```{r}
# Takes a subsetted list of functions from Hadley Advanced R
# Assigns each randomly to a student in the class
# 19 February 2017
# NJG

# Ensure that the same random number sequence is used by everyone.
set.seed(100) 

# The Hadley R functions:
firstToLearn <- c("str", "?")

operators <- c("%in%", "match", "=", "<-", "<<-", "$", "[",
               "[[", "head", "tail", "subset", "with", "assign", "get")
comparisons <- c("all.equal", "identical", "!=", "==", ">", ">=", "<", "<=",  "is.na", "complete.cases",  "is.finite")

basicMath <- c("*", "+", "-", "/", "^", "%%", "%/%", "abs", "sign", "acos", "asin", "atan", "atan2", "sin", "cos", "tan", "ceiling", "floor", "round", "trunc", "signif", "exp", "log", "log10", "log2", "sqrt", "max", "min", "prod", "sum", "cummax", "cummin", "cumprod", "cumsum", "diff", "pmax", "pmin", "range", "mean", "median", "cor", "sd", "var", "rle")

logicalSets <- c("&", "|", "!", "xor", "all", "any", "intersect", "union", "setdiff", "setequal", "which")

vectorsMatrices <- c("c", "matrix", "length", "dim", "ncol", "nrow", "cbind", "rbind", "names", "colnames", "rownames", "t", "diag", "sweep", "as.matrix", "data.matrix")

makingVectors <- c("c", "rep", "rep_len", "seq", "seq_len", "seq_along", "rev", "sample", "choose", "factorial", "combn", "is.character", "is.numeric", "is.logical", "as.character", "as.numeric", "as.logical")

listsDataFrames <- c("list", "unlist",  "data.frame", "as.data.frame", "split", "expand.grid")

output <- c("print", "cat", "message", "warning", "dput", "format", "sink", "capture.output", "sprintf")

readingWritingData <- c("data", "count.fields", "read.csv", "write.csv", "read.delim", "write.delim", "read.fwf", "readLines", "writeLines", "readRDS", "saveRDS", "load", "save")

# Combine all of the function lists and randomize the order:
RFunctions <- c(firstToLearn, operators, comparisons, basicMath, logicalSets, vectorsMatrices, makingVectors, listsDataFrames, output, readingWritingData)

RFunctions <- sample(RFunctions)

# Create class list
classNames <- c("Alger", "Ashlock", "Burnham", "Clark", "Kazenal", "Keller", "Looi", "Makhukov", "Mickuki", "Nevins", "Southgate") 

# Assign functions
functionAssignments <- rep_len(classNames, length.out=length(RFunctions))

# Bind the two columns into a data frame
functionsFinal <- data.frame(functionAssignments,RFunctions)
```
2. Illustrate your knowledge of basic subsetting methods by creating and printing a data frame that shows only the 13 functions that you are responsible for.

3. In your markdown file for this assignment, create an entry for each of the 13 functions that has been randomly assigned to you. Use a level-3 header for the name of the function in backticks, followed by a level-4 header with your name. For example:

```
### `as.data.frame`
#### Nicholas J. Gotelli
```
4. Below this entry, add a few sentences of markdown text to describe what the function does, and what the inputs and outputs are, and what the default settings are. Write in plain English in a way that will make the function easy to understand for you and everyone else. Obviously, you will want to go first to the help entry for that function to see what is listed, but you can probably do a much better job than that.

5. After your paragraph of explanation, add a chunk of R code, and illustrate the use of the function using some simple inputs and outputs. Annotate your code with comments, especially to illustrate some of the variations on the inputs and how they affect what you get.

Do this on a single html page for each of the 13 functions that have been assigned to you. Some will be very easy and simple, but others may be more complex. Do the easy ones first, and then circle back to study and work on the tough ones. Don't be shy about asking for help from Lauren if you get stumped. 

