---
title: 'Homework #7'
author: "Nicholas J. Gotelli"
date: 'February 28, 2017'
output:
  html_document:
    highlight: tango
    theme: united
  pdf_document: default
---
This week's exercise will be to continue and finish the functions that have been assigned to you. 

1. If you already finished all of your functions last time, you can
- help someone else in the class who is struggling with one of the functions
- add new functions to your list that you have found helpful in your own work in R
- read Chapter 4 of Hadley's book [Advanced R](http://adv-r.had.co.nz/) to find some new functions that you are curious about.

2. On a single .Rmd page, include all of the functions that were assigned to you last week, and add any new ones from this week. Some functions will be very easy and simple, but others may be more complex. Do the easy ones first, and then circle back to study and work on the tough ones. Don't be shy about asking for help from Lauren or your classmates if you get stumped. 

7. Once your functions are complete, copy and paste each of them into its own separate text file. The first line of the textfile should be the title `### as.data.frame`, and the next lines should have your name, your markdown text, and your r chunk.

8. Save this little snippet into a file that uses the name of the function as the file name. In this case, you would save the file as `AsDataFrame.txt`. If the function is a symbol rather than a named character string, name your file with the corresponding word. For example, if you wrote a function for `[`, you would name your snippet `SquareBracket.txt`.

9. Knit your `.Rmd` file into an html file and post it to your portfolio.

10. Turn in to Lauren your text snippets on a flash drive.

11. Lauren will show you how you can use a simple shell command to concatenate these snippets into a single text file. She will copy that text file into a standard `.Rmd` file, which I will knit to an html and post on the course web page.

12. This is a very general strategy for learning new tools in R. Whenever you figure out how to do something, create an `.Rmd` file, add some markdown text and a chunk of code, give the file an informative name, and then knit it to an html file. This collection of html files is your own personal cookbook for doing useful things in R. I have on my own Dropbox a folder I call `R Vignettes` where I put all of these things. Whenever I am trying to remember how to do something, I scan that folder until I find the html that has what I need. This is one of the fastest ways to become proficient at R and build up a library of useful tools.
