---
title: 'Lecture #1: Introduction'
author: "Nicholas J. Gotelli"
date: "14 January 2020"
output:
  html_document:
    highlight: tango
    keep_md: yes
    theme: united
  pdf_document: default
---

___

### Introductions

- me
- Lauren

### "The Workflow"
- get data
    + hand entry
    + machine generated
    + scraped from Web
- wrangle data
    + transform and format for analysis
- analyze data
    + statistical analysis
    + simulation modeling, forecasting
- graph data
    + exploratory graphics
    + publication quality graphics
- write paper
    + tools for speeding up writing process
    
#### Traditional and Modern Computational Tools
- Traditional
    + Word/Excel/Powerpoint
    + SAS/SPSS/JMP for stats
    + Sigmaplot for graphics

- Commercial
- Proprietary
- Expensive, availability of updates
- Code not available to modify, improve
- File formats usually not compatable
- Poor tools for documentation, transparency

- Modern
    + LaTeX/Markdown/Typora/Overleaf (instead of Word)
    + plain-text editors (instead of Excel)
    + Beamer slides (instead of Powerpoint)
    + R (instead of stats and graphics packages)
  
- Plain text files
    + always can be opened and read by humans
    + requires special plain-text editor
    + illustrate Atom editor
    
- Advantages of Modern
    + free, open source
    + files always usable and readable
    + huge network of expert users (Wikipedia style)
    + less vulnerable to hackers and malware
    
- Learning to code
    + deeper understanding of problem
    + hypothesis testing
    + life long habit of learning and staying abreast of field
    
- Three kinds of students
    + complete beginners (no chance for bad habits)
    + currently use R (R user, but not a programmer)
    + experienced programmer (still useful for refresher of basics, new tools)
    
    
- Prerequisites
    + Familiarity with files/folders basic operations clicking, dragging, creating, deleting files
    + Familiarity with unholy trio (Word, Excel, Powerpoint)
    + Familiarity with basic statistics (mean, variance, p-value, regression, anova)
    + Familiarity with basic probability (normal, uniform)
    
### Course Structure

#### Lectures
- bring fully charged computer
- code line by line with me
- help your neighbor
- help me

#### Labs
- do homeworks intended for in class work
- post work to your GitHub portfolio
- 5 - 8 hours of work a week

#### Grading
- portfolio
- participation
- presentation
    
### Course content
- Computational tools
    + plain-text editors (use for all files and for writing)
    + markdown (simple word processing)
    + LaTeX (for formatting equations)
    + regular expressions (search and find on steroids)
    + git and GitHub (for organizing and storing data and scripts)
    + web page construction and maintenance (using markdown and GitHub)
    + shell commands (for using GitHub and other programs)
    + learning new tools (doing new things in R)
    + Slack (better than e-mail)
    + whereby
    
- Programming Foundations in R
    + Basic coding in R studio (scripts, sourcing, console, data structures, functions)
    + Foundational Programming Methods (annotating code, for loops, control structures, ifelse, and much more) 
    + Data Files (creating and annotating your scripts and data files for safe storage and archival use)

- Advanced Topics
    + `dplyr` for data wrangling
    + Graphics (creating publication quality graphics with `ggplot2`)
    + Basic experimental designs (ANOVA, regression, logistic regression, contingency table)
    + Data simulation (normal, uniform, poisson, beta, gamma distributions)
    + Advanced git commands
    + Advanced shell commands
    + Manuscript production in LaTeX
    + Slide presentations in LaTeX
    + Thinking on paper

### Non-computational tools
- A good notebook
- Touch typing

### Setting up Rstudio
- Step through global options

